version: '3'
services:
  spring-app:
    build: ./  # Replace with your actual Spring app path
    ports:
      - "8080:8080"  # Map host port to container port
    depends_on:
      - mongodb

  mongodb:
    image: mongo
    ports:
      - "27017:27017"  # Map host port to container port
    volumes:
      - mongodb_data:/data/db  # Mount a volume for MongoDB data persistence

volumes:
  mongodb_data:
